# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'
target 'GlideDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GlideDemo
  pod 'AlamofireImage', '~> 3.5'
end
